// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
//import 'firebase_options.dart';

// ...

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoNvnjz-J3-ttiqslc8Y1oDpD-s7OFSng',
    appId: '1:868634398702:android:9def671d226570af7848ff',
    messagingSenderId: '868634398702',
    projectId: 'addis-stay-ce1e2',
    storageBucket: 'addis-stay-ce1e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVnX2LNpWBv3qWbb2wvGms1H2HlEhzTu4',
    appId: '1:868634398702:ios:1d85468826ee0e817848ff',
    messagingSenderId: '868634398702',
    projectId: 'addis-stay-ce1e2',
    storageBucket: 'addis-stay-ce1e2.appspot.com',
    iosBundleId: 'com.example.mobileApplicationProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzJd-s-8X3oA6jcF6yzbf4X3rxIwBCo_c',
    appId: '1:868634398702:web:0124cb87796f9aed7848ff',
    messagingSenderId: '868634398702',
    projectId: 'addis-stay-ce1e2',
    authDomain: 'addis-stay-ce1e2.firebaseapp.com',
    storageBucket: 'addis-stay-ce1e2.appspot.com',
    measurementId: 'G-6NKEN6X0PQ',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzJd-s-8X3oA6jcF6yzbf4X3rxIwBCo_c',
    appId: '1:868634398702:web:7ccf8724dc724c3a7848ff',
    messagingSenderId: '868634398702',
    projectId: 'addis-stay-ce1e2',
    authDomain: 'addis-stay-ce1e2.firebaseapp.com',
    storageBucket: 'addis-stay-ce1e2.appspot.com',
    measurementId: 'G-PVVN469ZFT',
  );

}